### ISSUE TITLE
Scoped scss is not scoped

### ISSUE THREAD

**Issue by ItsPierre** [jojomatik/nuxt-3-base#173] opened 2023-03-26 20:23 UTC
**Describe the bug**
SCSS in a scoped `style` tag is not scoped anymore.
In a clean Vue3-project, this still works.

CSS in a scoped `style` tag will apply to the whole application.

**To Reproduce**
1. Add a `scoped` style for a class `test`
2. Add the class `test` in another component to a div
3. See, that this div gets the style

**Expected behavior**
Scoped scss should only apply to the component in which it is defined.

**Comment by jojomatik** [comment] 2023-04-23 12:17
Hi @ItsPierre, sorry for the late reply. I've tried to reproduce but I don't succeed. 

Please provide an reproduction example, otherwise I will close the issue.

**Comment by ItsPierre** [comment] 2023-05-24 17:31
I just tested it again and the css is not scoped.

Just create 2 components, use one in the other.

Inner component gets a div with a width and heigth and a class `test`.
Now, add 
```
<style lang="scss" scoped>
.test {
background-color: red;
}
</style>
```
to the outer component and see, that the inner component gets the background color.

**Comment by jojomatik** [comment] 2023-05-28 21:45
Please fork and push a reproduction example. I'm still not able to reproduce.

**Comment by jojomatik** [comment] 2023-05-28 21:47
Please fork and push a reproduction example. I'm still not able to reproduce.

**Comment by jojomatik** [comment] 2023-05-30 21:17
We've just checked. According to the [vue-loader docs](https://vue-loader.vuejs.org/guide/scoped-css.html#child-component-root-elements) a child component's root node is affected by `scoped` styles of the parent component. All other nodes should be unaffected by the `scoped` css. This is the case.

Therefore, this behaviour is by design!

**Closed as completed by jojomatik** 2023-05-30 21:17 UTC
Labels: type:fix
